# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Tokyo Night
#include current-theme.conf
include ~/.cache/wal/colors-kitty.conf
# END_KITTY_THEME

font_family JetBrains Mono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto 

font_size 21

background_opacity 0.85
dynamic_background_opacity yes

allow_remote_control yes

cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

map ctrl+backspace send_text all \x17

confirm_os_window_close 0

