backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

fading = false;
no-fading-openclose = true;
no-fading-destroyed-argb = true;

fade-delta = 0;

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 3;

